In [21]:
import pandas as pd

In [22]:
df = pd.read_csv(r'C:\Users\kerem\Desktop\pandas\data\youtube.csv')

df.head()

,Title,Published_date,Views,Likes,Comments
0,It's a Normal Smartwatch Until...,2023-03-20T18:03:22Z,160710,19267,346
1,Desk Tour & Daily Tech Update 2023!,2023-03-16T19:45:29Z,1643246,67821,2274
2,What is Happening with Samsung's Camera?,2023-03-13T19:26:48Z,2645555,143144,6904
3,The Yellow iPhone 14: Love it or Hate it?,2023-03-09T17:43:16Z,1912716,131903,2270
4,This Feature is Underrated!,2023-03-05T16:20:33Z,2245846,164597,1571

In [14]:
df.shape
df.info
df = df.drop(columns=df.columns[-2:])

In [23]:
(
    df.groupby(by='Views')
        .agg({
            'Views' : ['sum','mean'],
            'Comments' : ['sum','mean']

        })



)

             Views             Comments
               sum        mean      sum          mean
Views
0                0         0.0    28157   3128.555556
2075          2075      2075.0       55     55.000000
2099          2099      2099.0       22     22.000000
2152          2152      2152.0       10     10.000000
2169          2169      2169.0       27     27.000000
...            ...         ...      ...           ...
16758450  16758450  16758450.0    30511  30511.000000
18275423  18275423  18275423.0    24376  24376.000000
21928289  21928289  21928289.0     9437   9437.000000
23250214  23250214  23250214.0    11561  11561.000000
39872117  39872117  39872117.0    14535  14535.000000

[1514 rows x 4 columns]

In [34]:
def calculate_titles(tag: str) -> int:
    return len(tag.split('|'))

df['title_count'] = df['Title'].apply(calculate_titles)

df[['Views', 'Likes', 'title_count']]

        Views   Likes  title_count
0      160710   19267            1
1     1643246   67821            1
2     2645555  143144            1
3     1912716  131903            1
4     2245846  164597            1
...       ...     ...          ...
1520   136330    1656            1
1521  4723387  236581            1
1522   189052    2777            1
1523   182531    2325            1
1524   825396   18522            1

[1525 rows x 3 columns]

In [35]:
df.query('Likes<5000')[['Views', 'Likes','Title']].sort_values(by='Likes',ascending=False)

       Views  Likes                                              Title
1080  398883   4924                   Google Project Glass: Explained!
1135  205219   4912                                    The Dream Phone
996    71787   4894               Nexus 4 & Nexus 7 Giveaway! [CLOSED]
1046  154956   4885  GIVEAWAY: Fastest Mac Mini in the World! [Closed]
1017  104587   4710                           $600 Gaming PC Giveaway!
...      ...    ...                                                ...
1365   30014      0    Call of Duty Modern Warfare 2 Gameplay Footage!
1212   18936      0                          Firefox 4 Beta 1 Download
1209    9804      0                                Scrolling Comments!
1202   20981      0            GIVEAWAY: Beats by Dre Solo HD [Closed]
1206   11586      0                       MKBHD Intro Contest [CLOSED]

[466 rows x 3 columns]