In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r'C:\Users\kerem\Desktop\pandas\data\clean_auto.csv')

In [8]:
df.columns

df.isnull().sum()

symbling             0
normalized_losses    0
make                 0
num_of_doors         0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_of_cylinders     0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
highway_mpg          0
price                0
city-L/100km         0
horsepower_binned    0
diesel               0
gas                  0
aspiration_std       0
aspiration_turbo     0
dtype: int64

In [9]:
missing_values_df = df.isnull()
missing_values_df.head()
for column_name in missing_values_df.columns.tolist():
    print(column_name)

symbling
normalized_losses
make
num_of_doors
body_style
drive_wheels
engine_location
wheel_base
length
width
height
curb_weight
engine_type
num_of_cylinders
engine_size
fuel_system
bore
stroke
compression_ratio
horsepower
peak_rpm
highway_mpg
price
city-L/100km
horsepower_binned
diesel
gas
aspiration_std
aspiration_turbo

In [10]:
df.replace(
    to_replace='?',
    value=np.nan,
    inplace=True
)

df.head()

,symbling,normalized_losses,make,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,width,...,horsepower,peak_rpm,highway_mpg,price,city-L/100km,horsepower_binned,diesel,gas,aspiration_std,aspiration_turbo
0,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,111,5000.0,27,13495.0,11.190476,low,0,1,1,0
1,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,111,5000.0,27,16500.0,11.190476,low,0,1,1,0
2,1,122,alfa-romero,two,hatchback,rwd,front,94.5,0.822681,0.909722,...,154,5000.0,26,16500.0,12.368421,medium,0,1,1,0
3,2,164,audi,four,sedan,fwd,front,99.8,0.848630,0.919444,...,102,5500.0,30,13950.0,9.791667,low,0,1,1,0
4,2,164,audi,four,sedan,4wd,front,99.4,0.848630,0.922222,...,115,5500.0,22,17450.0,13.055556,low,0,1,1,0

In [11]:
df['normalized_losses']=df['normalized_losses'].replace(
    to_replace=np.nan,
    value=df['normalized_losses'].astype(float).mean()
)

df.head()

,symbling,normalized_losses,make,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,length,width,...,horsepower,peak_rpm,highway_mpg,price,city-L/100km,horsepower_binned,diesel,gas,aspiration_std,aspiration_turbo
0,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,111,5000.0,27,13495.0,11.190476,low,0,1,1,0
1,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,111,5000.0,27,16500.0,11.190476,low,0,1,1,0
2,1,122,alfa-romero,two,hatchback,rwd,front,94.5,0.822681,0.909722,...,154,5000.0,26,16500.0,12.368421,medium,0,1,1,0
3,2,164,audi,four,sedan,fwd,front,99.8,0.848630,0.919444,...,102,5500.0,30,13950.0,9.791667,low,0,1,1,0
4,2,164,audi,four,sedan,4wd,front,99.4,0.848630,0.922222,...,115,5500.0,22,17450.0,13.055556,low,0,1,1,0

In [12]:
df['num_of_doors'].value_counts().idxmax()

'four'

In [19]:
#data standartization
df['highway-L/100km'] = 235 / df['highway_mpg']


hw = df[["make", "city-L/100km", "highway-L/100km"]]

print(hw.head())

          make  city-L/100km  highway-L/100km
0  alfa-romero     11.190476         8.703704
1  alfa-romero     11.190476         8.703704
2  alfa-romero     12.368421         9.038462
3         audi      9.791667         7.833333
4         audi     13.055556        10.681818

In [20]:
print(df.columns)

Index(['symbling', 'normalized_losses', 'make', 'num_of_doors', 'body_style',
       'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width',
       'height', 'curb_weight', 'engine_type', 'num_of_cylinders',
       'engine_size', 'fuel_system', 'bore', 'stroke', 'compression_ratio',
       'horsepower', 'peak_rpm', 'highway_mpg', 'price', 'city-L/100km',
       'horsepower_binned', 'diesel', 'gas', 'aspiration_std',
       'aspiration_turbo', 'highway-L/100km'],
      dtype='object')

In [22]:
#data-normalization

df['length'] = df['length'] / df['length'].max()
df['width'] = df['width'] / df['width'].max()
df['height'] = df['height'] / df['height'].max()

df[['length', 'width', 'height']].describe()

           length       width      height
count  201.000000  201.000000  201.000000
mean     0.837102    0.915126    0.899108
std      0.059213    0.029187    0.040933
min      0.678039    0.837500    0.799331
25%      0.801538    0.890278    0.869565
50%      0.832292    0.909722    0.904682
75%      0.881788    0.925000    0.928094
max      1.000000    1.000000    1.000000